baseURL = "https://daniellam.com/"
languageCode = "en-us"
title = "Daniel Lam"
theme = "seminyak"
googleAnalytics = "UA-47083218-1"

[params]
  theme_color = "#fcfbeb"
  color_palette = "yellow"
  background_image_url = "https://source.unsplash.com/aDK6P3G-AQc/"
  referrer_policy = "same-origin"
  google_fonts = "Oswald|Raleway"
